[package]
name = "api-speed-test"
version = "1.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
plotters = "0.3.7"